print("=" * 60)
print("GEOMETRIC PARTICLE PHYSICS PROJECT")
print("Initial Setup Complete!")
print("=" * 60)
print("\nProject Structure Created:")
print("• Geometric_Particle_Physics/")
print("  ├── data/")
print("  │   ├── raw/")
print("  │   ├── processed/")
print("  │   └── db/")
print("  ├── src/")
print("  └── setup_check.py")
print("\nNext: Install required packages")